Add unit tests
open-viz/grafana-sdk pull request #1
Opened 2021-12-13 13:09 UTC by pkbhowmick

Signed-off-by: Pulak Kanti Bhowmick <pulak@appscode.com>

2021-12-14 05:25 UTC, masudur-rahman requested changes

2021-12-14 05:25 UTC, masudur-rahman commented on .github/workflows/ci.yml
> +          ./bin/grafana-server
./bin/grafana-server &

2021-12-14 05:34 UTC, pkbhowmick commented on .github/workflows/ci.yml
> +          ./bin/grafana-server
Added

2021-12-27 12:40 UTC, masudur-rahman approved these changes
lgtm

2021-12-27 12:43 UTC, merged